name: Validation

on:
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          cache: npm
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
